service: cncb-esg-outbound

provider:
  name: aws
  runtime: nodejs22.x
  environment:
    REPO: JavaScript-Cloud-Native-Development-Cookbook
    OWNER: cozycole
    TOKEN: 

functions:
  listener:
    handler: handler.listener
    events:
      - stream:
          type: kinesis
          arn: ${cf:cncb-event-stream-${opt:stage}.streamArn}
          batchSize: 100
          startingPosition: TRIM_HORIZON
