# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: cozycole
service: cncb-create-stack

provider:
  name: aws

resources:
  Resources:
    ExampleBucket:
      Type: AWS::S3::Bucket
